[package]
name = "database"
version = "1.0.0"
edition = "2018"
publish = false

[[bin]]
name = "database"
path = "main.rs"

[dependencies]
marine-rs-sdk = "0.6.14"
marine-sqlite-connector = "0.5.0"
sql_lexer = "0.9.3"
fstrings = "0.2.3"
