[package]
name = "bitcoin-ledger"
version = "1.0.0"
edition = "2018"
publish = false

[[bin]]
name = "bitcoin-ledger"
path = "main.rs"

[dependencies]
marine-rs-sdk = "0.6.14"
bitcoin = "0.28.1"
serde_json = "1.0.81"
