[package]
name = "crypto"
version = "1.0.0"
edition = "2018"
publish = false

[[bin]]
name = "crypto"
path = "main.rs"

[dependencies]
marine-rs-sdk = "0.6.14"
base64 = "0.13.0"
md-5 = "0.10.1"
sha2 = "0.10.2"
