[package]
name = "crypto-price"
version = "1.0.0"
edition = "2018"
publish = false

[[bin]]
name = "crypto-price"
path = "main.rs"

[dependencies]
marine-rs-sdk = "0.6.14"
serde_json = "1.0.81"
fstrings = "0.2.3"
