modules_dir = "artifacts/"

[[module]]
name = "crypto"
logger_enabled = false
max_heap_size = "5 KiB"

[[module]]
name = "price"
logger_enabled = false
max_heap_size = "5 KiB"

  [module.mounted_binaries]
  curl = "/usr/bin/curl"
